---
on:
    pull_request:
        branches:
        - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v5
        - name: restore
          run: dotnet restore src/Web/Web.csproj
        - name: build
          run:  dotnet build --configuration=Release  src/Web/Web.csproj --no-restore
        - name: test
          run: dotnet test tests/UnitTests/UnitTests.csproj --logger "trx;LogFileName=test_results.trx"
        # 2. ఆ రిజల్ట్ ఫైల్‌ను GitHub Artifacts కి పబ్లిష్ చేసే స్టెప్
        - name: Publish Test Results
          uses: actions/upload-artifact@v4
          if: always() # టెస్ట్ ఫెయిల్ అయినా కూడా రిజల్ట్స్ పబ్లిష్ అవ్వాలి కాబట్టి ఇది ముఖ్యం
          with:
            name: dotnet-test-results
            path: "**/TestResults/*.trx"          
        - name: publish
          run: dotnet publish --configuration Release src/Web/Web.csproj --output published

        # 1. పబ్లిష్ అయిన ఫైల్స్‌ను జిప్ చేయడం
        - name: Zip the published artifact
          # ఇక్కడ మనం రిపోజిటరీ పేరు మరియు రన్ నంబర్‌తో జిప్ ఫైల్‌ను క్రియేట్ చేస్తున్నాము
          run: zip -r ${{ github.event.repository.name }}-${{ github.run_number }}.zip published

        # 2. జిప్ ఫైల్‌ను ఆర్టిఫ్యాక్ట్‌గా అప్‌లోడ్ చేయడం
        - name: Upload Published Zip
          uses: actions/upload-artifact@v4
          with:
            name: ${{ github.event.repository.name }}-${{ github.run_number }}
            path: ${{ github.event.repository.name }}-${{ github.run_number }}.zip          
